version: "3.7"

volumes:
  dbdata:

services:
  pg:
    image: docker.io/postgres:16.0
    environment:
      TZ: UTC
      POSTGRES_USER: paidy
      POSTGRES_PASSWORD: paidy
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5342:5432"
